server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0

logging:
  file:
    name: ${LOG_FILE_DIR:./logs/ecommerce_app.log}
  logback:
    rollingPolicy:
      max-file-size: ${LOGBACK_MAX_FILE_SIZE:50MB}
      max-history: ${LOGBACK_MAX_HISTORY:7}
      file-name-pattern: ${logging.file.name}.%d{yyyy-MM-dd}.%i.log
  level:
    org:
      springframework:
        security: ${SERVER_SECURITY_LOG_LEVEL:info}
    web: ${SERVER_WEB_LOG_LEVEL:info}
    root: ${SERVER_ROOT_LOG_LEVEL:info}
spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: ${SPRING_ENV:dev}
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: "100MB"
      max-request-size: "100MB"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true

  mail:
    host: ${SMTP_SERVER_HOST:smtp.gmail.com}
    port: ${SMTP_SERVER_PORT:587}
    username: ${SMTP_SERVER_USERNAME}
    password: ${SMTP_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SMTP_SERVER_AUTH:false}
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
          starttls.enable: true

  engine:
    template:
      prefix: classpath:/
      suffix: .html
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    enabled: true

app:
  baseUrl: ${APP_BASE_URL:http://localhost:8080}
  firebaseApiKey: AIzaSyCUyK9i5mknwnAIJc6Gl-bYDZ0MijHQTRg
  jwt:
    secretKey: ${JWT_SECRET}
    access-expired-in-minute: ${JWT_ACCESS_EXPIRES_MINUTE}
    refresh-expired-in-minute: ${JWT_REFRESH_EXPIRES_MINUTE}
  storage:
    upload:
      avatar: ./storage/upload/avatar
      product: ./storage/upload/product

